package Vista.venta;

import Controlador.ControladorGlobal;
import Vista.mercancia.frmMercancia;
import Vista.productos.frmProductos;

/**
 *
 * @author USUARIO
 */
public class frmVenta extends javax.swing.JFrame {
    //Atributos
    ControladorGlobal objGlobal;
    
    public frmVenta() {
        initComponents();
        //setLocationRelativeTo(this); //Para centrar el Jframe
        this.objGlobal = new ControladorGlobal(); // Para acceder a las funciones globales
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVentas = new javax.swing.JDesktopPane();
        btn_CerrarSesion = new javax.swing.JButton();
        btn_GoToProductos = new javax.swing.JButton();
        btnGoToMercancia = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnNuevaVenta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnVerVentas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelVentas.setBackground(new java.awt.Color(41, 41, 41));

        btn_CerrarSesion.setText("Cerrar Sesion");
        btn_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarSesionActionPerformed(evt);
            }
        });

        btn_GoToProductos.setText("Productos");
        btn_GoToProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GoToProductosActionPerformed(evt);
            }
        });

        btnGoToMercancia.setText("Mercancia");
        btnGoToMercancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToMercanciaActionPerformed(evt);
            }
        });

        jPanelVentas.setLayer(btn_CerrarSesion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelVentas.setLayer(btn_GoToProductos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelVentas.setLayer(btnGoToMercancia, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanelVentasLayout = new javax.swing.GroupLayout(jPanelVentas);
        jPanelVentas.setLayout(jPanelVentasLayout);
        jPanelVentasLayout.setHorizontalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVentasLayout.createSequentialGroup()
                .addContainerGap(672, Short.MAX_VALUE)
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_CerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_GoToProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGoToMercancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelVentasLayout.setVerticalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_CerrarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_GoToProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoToMercancia)
                .addContainerGap(395, Short.MAX_VALUE))
        );

        jMenu1.setText("Gestión de Ventas");

        jMnNuevaVenta.setText("Gestionar Ventas");
        jMnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnNuevaVentaActionPerformed(evt);
            }
        });
        jMenu1.add(jMnNuevaVenta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mostrar Ventas");

        jMnVerVentas.setText("Ver Ventas");
        jMnVerVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnVerVentasActionPerformed(evt);
            }
        });
        jMenu2.add(jMnVerVentas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelVentas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelVentas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnNuevaVentaActionPerformed
        // TODO add your handling code here:
        objGlobal.OpenJInternalFrame(new nuevaVenta(), jPanelVentas);
    }//GEN-LAST:event_jMnNuevaVentaActionPerformed

    private void jMnVerVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnVerVentasActionPerformed
        // TODO add your handling code here:
        objGlobal.OpenJInternalFrame(new mostrarVentas(), jPanelVentas);
    }//GEN-LAST:event_jMnVerVentasActionPerformed

    private void btn_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarSesionActionPerformed
        // TODO add your handling code here:
        objGlobal.CerrarSesion(this);
    }//GEN-LAST:event_btn_CerrarSesionActionPerformed

    private void btn_GoToProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GoToProductosActionPerformed
        // TODO add your handling code here:
        objGlobal.GoToOtherJFrame(new frmProductos(), this);
    }//GEN-LAST:event_btn_GoToProductosActionPerformed

    private void btnGoToMercanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToMercanciaActionPerformed
        // TODO add your handling code here:
        objGlobal.GoToOtherJFrame(new frmMercancia(), this);
    }//GEN-LAST:event_btnGoToMercanciaActionPerformed
  
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmVenta().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoToMercancia;
    private javax.swing.JButton btn_CerrarSesion;
    private javax.swing.JButton btn_GoToProductos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnNuevaVenta;
    private javax.swing.JMenuItem jMnVerVentas;
    public javax.swing.JDesktopPane jPanelVentas;
    // End of variables declaration//GEN-END:variables
}
