/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.venta;

import Controlador.ControladorGlobal;
import Controlador.ControladorProducto;
import Controlador.ControladorVenta;
import Modelo.Producto;
import Modelo.Ventas_Productos;
import Vista.main.Vista;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class nuevaVenta extends javax.swing.JInternalFrame {

    ControladorGlobal objGlobal;
    ControladorVenta objVenta;
    //Variables para el JList
    ControladorProducto objProducto;
    ArrayList<Producto> lstProductos;
    //Arreglo para guardar los ids de los productos seleccionados en el JList
    ArrayList<Ventas_Productos> lst_id_cantidad_producto;

    public nuevaVenta() {
        initComponents();
        inicializarLista();
        this.objGlobal = new ControladorGlobal();
        this.objVenta = new ControladorVenta(Vista.dataLogin);
        this.objProducto = new ControladorProducto();
        this.lstProductos = new ArrayList<>();
        this.lst_id_cantidad_producto = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        lbl_descripcion1 = new javax.swing.JLabel();
        lbl_Busqueda = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLstProductos = new javax.swing.JList<>();
        btn_VerFactura = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblVentaFind = new javax.swing.JTable();
        lblInformativo = new javax.swing.JLabel();
        jPanelNumerico = new javax.swing.JPanel();
        btnN0 = new javax.swing.JButton();
        btnN8 = new javax.swing.JButton();
        btnN7 = new javax.swing.JButton();
        btnN4 = new javax.swing.JButton();
        btnN5 = new javax.swing.JButton();
        btnN9 = new javax.swing.JButton();
        btnN6 = new javax.swing.JButton();
        btnN1 = new javax.swing.JButton();
        btnN3 = new javax.swing.JButton();
        btnN2 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel4.setText("Solo para busquedas");

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        lbl_descripcion1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_descripcion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_descripcion1.setText("PRODUCTOS");

        lbl_Busqueda.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_Busqueda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Busqueda.setText("ID");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.setEnabled(false);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("GESTIONAR VENTAS");

        lblTitulo.setBackground(new java.awt.Color(153, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Ventas");

        txt_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_id.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idKeyTyped(evt);
            }
        });

        jScrollPane1.setViewportView(jLstProductos);

        btn_VerFactura.setText("Ver Factura");
        btn_VerFactura.setEnabled(false);
        btn_VerFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerFacturaActionPerformed(evt);
            }
        });

        jTblVentaFind.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Venta", "Productos", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblVentaFind.setEnabled(false);
        jScrollPane2.setViewportView(jTblVentaFind);

        lblInformativo.setText("lbl seleccion productos");
        lblInformativo.setToolTipText("");
        lblInformativo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblInformativo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblInformativo.setFocusable(false);
        lblInformativo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnN0.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnN0.setText("0");
        btnN0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnN0ActionPerformed(evt);
            }
        });

        btnN8.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnN8.setText("8");
        btnN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnN8ActionPerformed(evt);
            }
        });

        btnN7.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnN7.setText("7");
        btnN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnN7ActionPerformed(evt);
            }
        });

        btnN4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnN4.setText("4");
        btnN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnN4ActionPerformed(evt);
            }
        });

        btnN5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnN5.setText("5");
        btnN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnN5ActionPerformed(evt);
            }
        });

        btnN9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnN9.setText("9");
        btnN9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnN9ActionPerformed(evt);
            }
        });

        btnN6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnN6.setText("6");
        btnN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnN6ActionPerformed(evt);
            }
        });

        btnN1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnN1.setText("1");
        btnN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnN1ActionPerformed(evt);
            }
        });

        btnN3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnN3.setText("3");
        btnN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnN3ActionPerformed(evt);
            }
        });

        btnN2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnN2.setText("2");
        btnN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnN2ActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnDelete.setText("<");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNumericoLayout = new javax.swing.GroupLayout(jPanelNumerico);
        jPanelNumerico.setLayout(jPanelNumericoLayout);
        jPanelNumericoLayout.setHorizontalGroup(
            jPanelNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumericoLayout.createSequentialGroup()
                .addComponent(btnN7)
                .addGap(4, 4, 4)
                .addComponent(btnN8)
                .addGap(4, 4, 4)
                .addComponent(btnN9)
                .addGap(4, 4, 4)
                .addComponent(btnDelete))
            .addGroup(jPanelNumericoLayout.createSequentialGroup()
                .addComponent(btnN4)
                .addGap(4, 4, 4)
                .addComponent(btnN5)
                .addGap(4, 4, 4)
                .addComponent(btnN6))
            .addGroup(jPanelNumericoLayout.createSequentialGroup()
                .addComponent(btnN1)
                .addGap(4, 4, 4)
                .addComponent(btnN2)
                .addGap(4, 4, 4)
                .addComponent(btnN3)
                .addGap(4, 4, 4)
                .addComponent(btnN0))
        );
        jPanelNumericoLayout.setVerticalGroup(
            jPanelNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumericoLayout.createSequentialGroup()
                .addGroup(jPanelNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnN7)
                    .addComponent(btnN8)
                    .addComponent(btnN9)
                    .addComponent(btnDelete))
                .addGap(10, 10, 10)
                .addGroup(jPanelNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnN4)
                    .addComponent(btnN5)
                    .addComponent(btnN6))
                .addGap(10, 10, 10)
                .addGroup(jPanelNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnN1)
                    .addComponent(btnN2)
                    .addComponent(btnN3)
                    .addComponent(btnN0)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_buscar)
                            .addComponent(btn_VerFactura))
                        .addGap(30, 30, 30)
                        .addComponent(jPanelNumerico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInformativo)))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btn_guardar)
                .addGap(64, 64, 64)
                .addComponent(btn_eliminar)
                .addGap(74, 74, 74)
                .addComponent(btn_limpiar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Busqueda)
                                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(btn_buscar)
                                .addGap(8, 8, 8)
                                .addComponent(btn_VerFactura))
                            .addComponent(jPanelNumerico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbl_descripcion1)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lblInformativo)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_guardar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_limpiar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos(); //Limpiamos los campos y habilitamos botones
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        if (obtenerProductosSeleccionados()) {
            objVenta.nuevaVenta(lst_id_cantidad_producto);
            limpiarCampos();
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        //Esto es para llenar el label informativo de como seleccionar varios productos
        this.lblInformativo.setText("<html><body> Para seleccionar varios productos"
                + "<br>mantenga presionado la tecla Ctrl"
                + "<br>y seleccione dando Click </body></html>");

        lstProductos = objProducto.obtenerProductos();
        DefaultListModel modeloLista = (DefaultListModel) jLstProductos.getModel();
        jLstProductos.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        for (Producto p : lstProductos) {
            modeloLista.addElement(p.getId() + " " + p.getNombre());
        }

    }//GEN-LAST:event_formInternalFrameOpened

    private void btn_VerFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerFacturaActionPerformed
        // TODO add your handling code here:
        int id_venta = Integer.parseInt(txt_id.getText());
        frmFactura factura = new frmFactura();
        factura.setId_Venta(id_venta);
        factura.setVisible(true);
        this.getParent().add(factura); // Agrega el JInternalFrame al contenedor padre
        factura.toFront(); // Asegura que se muestre encima del JInternalFrame actual
    }//GEN-LAST:event_btn_VerFacturaActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        limpiarJTable();
        if (!(txt_id.getText().isEmpty())) {

            int id_venta = Integer.parseInt(txt_id.getText());

            if (objVenta.ObtenerVentaId(id_venta) != null) {
                
                txt_id.setEnabled(false);
                btn_guardar.setEnabled(false);
                btn_VerFactura.setEnabled(true);
                btn_eliminar.setEnabled(true);
                ArrayList<ArrayList<String>> lstNombreProductos = objVenta.obtenerNombresProductosXVentaPorId(id_venta);
                DefaultTableModel modelo = (DefaultTableModel) jTblVentaFind.getModel();
                for (ArrayList<String> pr : lstNombreProductos) {
                    modelo.addRow(new Object[]{id_venta, pr.get(0), pr.get(1)});
                }
            } else {
                JOptionPane.showMessageDialog(this, "No se encontraron ventas con el id proporcionado");
            }

        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        int id_venta = Integer.parseInt(txt_id.getText());
        int opcion = JOptionPane.showConfirmDialog(this, "¿Esta seguro de eliminar?", "Eliminar Venta",
                JOptionPane.YES_NO_OPTION);
        if (opcion == 0) {
            if (objVenta.deleteVenta(id_venta)) {
                limpiarCampos();
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    //FUNCIONES APARTE
    private void limpiarCampos() {
        txt_id.setText("");
        btn_VerFactura.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_guardar.setEnabled(true);
        txt_id.setEnabled(true);
        this.lst_id_cantidad_producto.clear();
        limpiarJTable();
    }

    private void limpiarJTable() {
        //Obtenemos el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) jTblVentaFind.getModel();
        //Mientras hayan filas, las vamos a remover
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    //Funcion para obtener el id y la cantidad de los productos que se seleccionen en el JList
    private boolean obtenerProductosSeleccionados() {
        boolean isVentaProductoAgg = false;
        // Obtener el modelo del JList
        DefaultListModel listModelProductos = (DefaultListModel) jLstProductos.getModel();
        // Obtener los índices de los elementos seleccionados en el JList
        int[] indicesSeleccionados = jLstProductos.getSelectedIndices();
        //Para capturar el nombre del producto completo con su id y todo
        String productoSeleccionado;
        //Para splitear y separar el id y el nombre del producto
        String[] partesStringProducto;

        // Este for me obtiene todos los elementos seleccionados en el jList
        for (int indice : indicesSeleccionados) {
            // Obtener el elemento seleccionado en la posición 'indice' del modelo
            productoSeleccionado = (String) listModelProductos.getElementAt(indice);

            /*Dividimos en dos el producto seleccionado, quedando asi: [Id, Nombre] 
            entonces la posicion 0 contendra el id y la posicion 1 el nombre completo*/
            partesStringProducto = productoSeleccionado.split(" ", 2);

            // Entero que contendra el id del producto
            int id_producto = Integer.parseInt(partesStringProducto[0]);
            // String que contendra el nombre del producto
            String nombre_Producto = partesStringProducto[1];

            System.out.println("ID del producto: " + id_producto);
            System.out.println("NOMBRE del producto: " + nombre_Producto);

            int cantidad = CastearEntero(nombre_Producto);

            System.out.println("Cantidad: " + cantidad);

            if (cantidad != -400) {//Entonces si es un entero valido

                //Agregamos a la lista nuestro id del producto y su respectiva cantidad
                lst_id_cantidad_producto.add(new Ventas_Productos(id_producto, cantidad));
                isVentaProductoAgg = true;
            } else {
                lst_id_cantidad_producto.clear();
                return false;
                //Sal de la funcion ya que se cancelo el registro desde la funcion CastearEntero
            }
        }
        return isVentaProductoAgg;
    }

    //Funcion para castear, funcion usada en obtenerProductosSeleccionados
    //esta funcion recibe el nombre y pregunta en un JOptionPane la cantidad vendida del producto
    private int CastearEntero(String nombre_producto) {
        String strCantidad;

        do {
            strCantidad = JOptionPane.showInputDialog(this, "Cantidad vendida de " + nombre_producto);

            if (strCantidad == null) { //Se quiere cancelar la venta
                return -400; // Cierre funcion
            }
            try {
                int cantidad = Integer.parseInt(strCantidad);
                return cantidad;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese solo numeros");
                strCantidad = "mal";
            }
        } while (strCantidad.equals("mal"));
        return -400;
    }

    private void inicializarLista() {
        // Esta funcion es para inicializar la lista y poder mandarle nuestros datos apenas se abra el JInternalFrame
        DefaultListModel modeloListaProductos = new DefaultListModel();
        jLstProductos.setModel(modeloListaProductos);
    }

    private void txt_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyTyped
        // TODO add your handling code here:
        int keyCode = evt.getKeyChar();
        //Si da enter hacer click en buscar
        if (keyCode == 10) {
            btn_buscar.doClick();
        }
        objGlobal.prohibirIngresoNumeros(evt);
    }//GEN-LAST:event_txt_idKeyTyped

    private void btnN0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnN0ActionPerformed
        // TODO add your handling code here:
        manejoTecladoPantalla("0");
    }//GEN-LAST:event_btnN0ActionPerformed

    private void btnN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnN1ActionPerformed
        // TODO add your handling code here:
        manejoTecladoPantalla("1");
    }//GEN-LAST:event_btnN1ActionPerformed

    private void btnN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnN2ActionPerformed
        // TODO add your handling code here:
        manejoTecladoPantalla("2");
    }//GEN-LAST:event_btnN2ActionPerformed

    private void btnN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnN3ActionPerformed
        // TODO add your handling code here:
        manejoTecladoPantalla("3");
    }//GEN-LAST:event_btnN3ActionPerformed

    private void btnN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnN4ActionPerformed
        // TODO add your handling code here:
        manejoTecladoPantalla("4");
    }//GEN-LAST:event_btnN4ActionPerformed

    private void btnN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnN5ActionPerformed
        // TODO add your handling code here:
        manejoTecladoPantalla("5");
    }//GEN-LAST:event_btnN5ActionPerformed

    private void btnN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnN6ActionPerformed
        // TODO add your handling code here:
        manejoTecladoPantalla("6");
    }//GEN-LAST:event_btnN6ActionPerformed

    private void btnN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnN7ActionPerformed
        // TODO add your handling code here:
        manejoTecladoPantalla("7");

    }//GEN-LAST:event_btnN7ActionPerformed

    private void btnN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnN8ActionPerformed
        // TODO add your handling code here:
        manejoTecladoPantalla("8");
    }//GEN-LAST:event_btnN8ActionPerformed

    private void btnN9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnN9ActionPerformed
        // TODO add your handling code here:
        manejoTecladoPantalla("9");
    }//GEN-LAST:event_btnN9ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String quitarUnCaracter = txt_id.getText().length() > 0 ? txt_id.getText().substring(0, txt_id.getText().length() - 1) : "";
        if (txt_id.isEnabled()) {
            txt_id.setText(quitarUnCaracter);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void manejoTecladoPantalla(String numero) {
        if (txt_id.isEnabled()) {
            txt_id.setText(txt_id.getText() + numero);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnN0;
    private javax.swing.JButton btnN1;
    private javax.swing.JButton btnN2;
    private javax.swing.JButton btnN3;
    private javax.swing.JButton btnN4;
    private javax.swing.JButton btnN5;
    private javax.swing.JButton btnN6;
    private javax.swing.JButton btnN7;
    private javax.swing.JButton btnN8;
    private javax.swing.JButton btnN9;
    private javax.swing.JButton btn_VerFactura;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jLstProductos;
    private javax.swing.JPanel jPanelNumerico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblVentaFind;
    private javax.swing.JLabel lblInformativo;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JLabel lbl_Busqueda;
    public javax.swing.JLabel lbl_descripcion1;
    public javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
