/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.mercancia;

import Controlador.ControladorGlobal;
import Vista.productos.frmProductos;
import Vista.venta.frmVenta;

/**
 *
 * @author USUARIO
 */
public class frmMercancia extends javax.swing.JFrame {

    //Atributos
    ControladorGlobal objGlobal;
    
    public frmMercancia() {
        initComponents();
        //setLocationRelativeTo(this); //Esto es para centrar el frame
        objGlobal = new ControladorGlobal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMercancia = new javax.swing.JDesktopPane();
        btnCerrarSesion = new javax.swing.JButton();
        btnGoProductos = new javax.swing.JButton();
        btnGoVentas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnNuevaMercancia = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnVerMercancia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMercancia.setBackground(new java.awt.Color(41, 41, 41));

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnGoProductos.setText("Productos");
        btnGoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoProductosActionPerformed(evt);
            }
        });

        btnGoVentas.setText("Ventas");
        btnGoVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoVentasActionPerformed(evt);
            }
        });

        jPanelMercancia.setLayer(btnCerrarSesion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelMercancia.setLayer(btnGoProductos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelMercancia.setLayer(btnGoVentas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanelMercanciaLayout = new javax.swing.GroupLayout(jPanelMercancia);
        jPanelMercancia.setLayout(jPanelMercanciaLayout);
        jPanelMercanciaLayout.setHorizontalGroup(
            jPanelMercanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMercanciaLayout.createSequentialGroup()
                .addContainerGap(617, Short.MAX_VALUE)
                .addGroup(jPanelMercanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGoProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGoVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMercanciaLayout.setVerticalGroup(
            jPanelMercanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMercanciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoVentas)
                .addContainerGap(362, Short.MAX_VALUE))
        );

        jMenu1.setText("Gestión de Mercancia");

        jMnNuevaMercancia.setText("Gestionar Mercancia");
        jMnNuevaMercancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnNuevaMercanciaActionPerformed(evt);
            }
        });
        jMenu1.add(jMnNuevaMercancia);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mostrar Mercancia");

        jMnVerMercancia.setText("Ver Mercancia");
        jMnVerMercancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnVerMercanciaActionPerformed(evt);
            }
        });
        jMenu2.add(jMnVerMercancia);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMercancia)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMercancia)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnNuevaMercanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnNuevaMercanciaActionPerformed
        // TODO add your handling code here:
        objGlobal.OpenJInternalFrame(new nuevaMercancia(), jPanelMercancia);
    }//GEN-LAST:event_jMnNuevaMercanciaActionPerformed

    private void jMnVerMercanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnVerMercanciaActionPerformed
        // TODO add your handling code here:
        objGlobal.OpenJInternalFrame(new mostrarMercancia(), jPanelMercancia);
    }//GEN-LAST:event_jMnVerMercanciaActionPerformed

    private void btnGoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoProductosActionPerformed
        // TODO add your handling code here:
        objGlobal.GoToOtherJFrame(new frmProductos(), this);
    }//GEN-LAST:event_btnGoProductosActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        objGlobal.CerrarSesion(this);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnGoVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoVentasActionPerformed
        // TODO add your handling code here:
        objGlobal.GoToOtherJFrame(new frmVenta(), this); 
    }//GEN-LAST:event_btnGoVentasActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmMercancia().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGoProductos;
    private javax.swing.JButton btnGoVentas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnNuevaMercancia;
    private javax.swing.JMenuItem jMnVerMercancia;
    private javax.swing.JDesktopPane jPanelMercancia;
    // End of variables declaration//GEN-END:variables
}
