/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.mercancia;

import Controlador.ControladorGlobal;
import Controlador.ControladorMercancia;
import Modelo.Mercancia;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class nuevaMercancia extends javax.swing.JInternalFrame {

    //Atributos
    ControladorMercancia objMercancia;
    ControladorGlobal objGlobal;

    public nuevaMercancia() {
        initComponents();
        objMercancia = new ControladorMercancia(); //Pasamos el controlador login para acceder al usuario
        objGlobal = new ControladorGlobal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        lbl_Busqueda = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        cbx_TipoMercancia = new javax.swing.JComboBox<>();
        txt_descripcion = new javax.swing.JTextField();
        lbl_cantidad = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        lbl_descripcion1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("GESTIONAR MERCANCIA");

        lblTitulo.setBackground(new java.awt.Color(153, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("MERCANCIA");

        txt_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_id.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idKeyTyped(evt);
            }
        });

        jLabel4.setText("Solo para busquedas");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        lbl_Busqueda.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_Busqueda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Busqueda.setText("ID");

        lbl_descripcion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_descripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_descripcion.setText("DESCRIPCION");

        cbx_TipoMercancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plato", "Queso", "Carnes", "Ripio", "Maicito", "Cubiertos" }));

        lbl_cantidad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_cantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cantidad.setText("STOCK");

        txt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyTyped(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.setEnabled(false);
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.setEnabled(false);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        lbl_descripcion1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_descripcion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_descripcion1.setText("CATEGORIA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbl_Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(131, 131, 131)
                .addComponent(lbl_descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btn_buscar)
                .addGap(20, 20, 20)
                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(cbx_TipoMercancia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(lbl_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(lbl_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btn_guardar)
                .addGap(44, 44, 44)
                .addComponent(btn_modificar)
                .addGap(37, 37, 37)
                .addComponent(btn_eliminar)
                .addGap(34, 34, 34)
                .addComponent(btn_limpiar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Busqueda)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_descripcion1)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscar)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_TipoMercancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cantidad)
                    .addComponent(lbl_descripcion))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_guardar)
                    .addComponent(btn_modificar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_limpiar))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        if (!txt_id.getText().isEmpty()) {
            int mrId = Integer.parseInt(txt_id.getText());
            Mercancia mrFind = objMercancia.obtenerMercanciaId(mrId);
            if (mrFind != null) { //Encontro algo
                txt_id.setEnabled(false); //Inhabilitamos el campo id para que no lo modifique
                btn_guardar.setEnabled(false);//Inhabilitamos el btn de guardar para que no guarde datos repetidos
                btn_modificar.setEnabled(true);
                btn_eliminar.setEnabled(true);
                txt_descripcion.setText(mrFind.getDescripcion());
                txt_cantidad.setText("" + mrFind.getCantidad());
                for (int i = 0; i < cbx_TipoMercancia.getItemCount(); i++) {
                    if (cbx_TipoMercancia.getItemAt(i).equals(mrFind.getCategoria())) {
                        cbx_TipoMercancia.setSelectedItem(mrFind.getCategoria());
                    }
                }
            }
        }

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos(); //Limpiamos los campos y habilitamos botones
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        if (!(txt_descripcion.getText().isEmpty() && txt_cantidad.getText().isEmpty())) {
            String categoria = cbx_TipoMercancia.getSelectedItem().toString();
            String descripcion = txt_descripcion.getText();
            int cantidad = Integer.parseInt(txt_cantidad.getText());
            Mercancia newMercancia = new Mercancia(0, categoria, descripcion, cantidad);
            if (objMercancia.AgregarMercancia(newMercancia)) {
                limpiarCampos();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Faltan Datos");
            txt_descripcion.requestFocus();
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
        int mr_id = Integer.parseInt(txt_id.getText());
        String categoria = cbx_TipoMercancia.getSelectedItem().toString();
        String descripcion = txt_descripcion.getText();
        int cantidad = Integer.parseInt(txt_cantidad.getText());
        Mercancia mr = new Mercancia(mr_id, categoria, descripcion, cantidad);
        boolean isUpdate = objMercancia.actualizarMercancia(mr);
        if(isUpdate){
            limpiarCampos();
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        int mr_id = Integer.parseInt(txt_id.getText());
        int opcion = JOptionPane.showConfirmDialog(this, "¿Desea eliminar la mercancia?",
                "Confirmacion", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            objMercancia.eliminarMercancia(mr_id);
            limpiarCampos();
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void txt_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyTyped
        // TODO add your handling code here:
        objGlobal.prohibirIngresoNumeros(evt);
    }//GEN-LAST:event_txt_idKeyTyped

    private void txt_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyTyped
        // TODO add your handling code here:
        objGlobal.prohibirIngresoNumeros(evt);
    }//GEN-LAST:event_txt_cantidadKeyTyped

    private void limpiarCampos() {
        txt_id.setText("");
        txt_descripcion.setText("");
        txt_cantidad.setText("");
        txt_id.setEnabled(true);
        btn_guardar.setEnabled(true);
        btn_modificar.setEnabled(false);
        btn_eliminar.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> cbx_TipoMercancia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JLabel lbl_Busqueda;
    public javax.swing.JLabel lbl_cantidad;
    public javax.swing.JLabel lbl_descripcion;
    public javax.swing.JLabel lbl_descripcion1;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_descripcion;
    public javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
