package Vista.productos;
import Controlador.ControladorGlobal;
import Vista.mercancia.frmMercancia;
import Vista.venta.frmVenta;
/**
 *
 * @author USUARIO
 */
public class frmProductos extends javax.swing.JFrame {
    
    ControladorGlobal objGlobal;
    
    public frmProductos() {
        initComponents();
        //setLocationRelativeTo(this); // Para centrar el Jframe
        objGlobal = new ControladorGlobal(); // Para acceder a todas las funciones globales
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProducto = new javax.swing.JDesktopPane();
        btnCerrarSesion = new javax.swing.JButton();
        btnGoMercancia = new javax.swing.JButton();
        btnGoVentas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCrearProducto = new javax.swing.JMenu();
        jMItemNuevoProducto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnItemVerProductos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelProducto.setBackground(new java.awt.Color(41, 41, 41));

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnGoMercancia.setText("Mercancia");
        btnGoMercancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoMercanciaActionPerformed(evt);
            }
        });

        btnGoVentas.setText("Ventas");
        btnGoVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoVentasActionPerformed(evt);
            }
        });

        jPanelProducto.setLayer(btnCerrarSesion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelProducto.setLayer(btnGoMercancia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelProducto.setLayer(btnGoVentas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanelProductoLayout = new javax.swing.GroupLayout(jPanelProducto);
        jPanelProducto.setLayout(jPanelProductoLayout);
        jPanelProductoLayout.setHorizontalGroup(
            jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductoLayout.createSequentialGroup()
                .addContainerGap(618, Short.MAX_VALUE)
                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGoMercancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGoVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelProductoLayout.setVerticalGroup(
            jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoMercancia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoVentas)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        mnCrearProducto.setText("Gestion de Productos");

        jMItemNuevoProducto.setText("Gestionar Productos");
        jMItemNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemNuevoProductoActionPerformed(evt);
            }
        });
        mnCrearProducto.add(jMItemNuevoProducto);

        jMenuBar1.add(mnCrearProducto);

        jMenu2.setText("Mostrar Productos");

        jMnItemVerProductos.setText("Ver Productos");
        jMnItemVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnItemVerProductosActionPerformed(evt);
            }
        });
        jMenu2.add(jMnItemVerProductos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelProducto)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelProducto)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMItemNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemNuevoProductoActionPerformed
        // TODO add your handling code here:
        objGlobal.OpenJInternalFrame(new nuevoProducto(), jPanelProducto);
    }//GEN-LAST:event_jMItemNuevoProductoActionPerformed

    private void jMnItemVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnItemVerProductosActionPerformed
        // TODO add your handling code here:
        objGlobal.OpenJInternalFrame(new MostrarProductos(), jPanelProducto);
    }//GEN-LAST:event_jMnItemVerProductosActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        objGlobal.CerrarSesion(this);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnGoMercanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoMercanciaActionPerformed
        // TODO add your handling code here:
        objGlobal.GoToOtherJFrame(new frmMercancia(), this);
    }//GEN-LAST:event_btnGoMercanciaActionPerformed

    private void btnGoVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoVentasActionPerformed
        // TODO add your handling code here:
        objGlobal.GoToOtherJFrame(new frmVenta(), this);
    }//GEN-LAST:event_btnGoVentasActionPerformed
//Quitamos el metodo run para que solo se abra con el logeo
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmProductos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGoMercancia;
    private javax.swing.JButton btnGoVentas;
    private javax.swing.JMenuItem jMItemNuevoProducto;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnItemVerProductos;
    private javax.swing.JDesktopPane jPanelProducto;
    private javax.swing.JMenu mnCrearProducto;
    // End of variables declaration//GEN-END:variables
}
